version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///app/data/database.sqlite
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
